<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="42800" started-at="2021-02-17T17:52:56Z" finished-at="2021-02-17T17:53:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="42800" started-at="2021-02-17T17:52:56Z" finished-at="2021-02-17T17:53:38Z">
      <class name="com.VW.tests.TestCase1">
        <test-method status="PASS" signature="setupSuite()[pri:0, instance:com.VW.tests.TestCase1@343f4d3d]" name="setupSuite" is-config="true" duration-ms="964" started-at="2021-02-17T23:22:55Z" finished-at="2021-02-17T23:22:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupSuite -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.VW.tests.TestCase1@343f4d3d]" name="setup" is-config="true" duration-ms="41830" started-at="2021-02-17T23:22:56Z" finished-at="2021-02-17T23:23:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="logincheck()[pri:0, instance:com.VW.tests.TestCase1@343f4d3d]" name="logincheck" duration-ms="97" started-at="2021-02-17T23:23:37Z" finished-at="2021-02-17T23:23:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.VW.utility.ExcelDataProvider.getStringData(ExcelDataProvider.java:37)
	at com.VW.tests.TestCase1.logincheck(TestCase1.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logincheck -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.VW.tests.TestCase1@343f4d3d]" name="tearDown" is-config="true" duration-ms="861" started-at="2021-02-17T23:23:37Z" finished-at="2021-02-17T23:23:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.VW.tests.TestCase1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
